GET http://localhost:3000/api/patients HTTP/1.1
###

GET http://localhost:3000/api/patients/d2773598-f723-11e9-8f0b-362b9e155667 HTTP/1.1
###

POST http://localhost:3000/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "1953-02-25",
  "ssn": "250253-021F",
  "gender": "male",
  "occupation": "Traveling Salesman"
}
###

POST http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
Content-Type: application/json

{
  "date": "2024-08-17",
  "specialist": "MD House",
  "type": "HealthCheck",
  "description": "HealthCheck POST test",
  "healthCheckRating": 0,
  "diagnosisCodes": ["J03.0", "L60.1"]
}
###

POST http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
Content-Type: application/json

{
  "date": "2024-08-17",
  "specialist": "MD House",
  "type": "OccupationalHealthcare",
  "description": "OccupationalHealthcare POST test",
  "employerName": "Self-Employed"
}
###

POST http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
Content-Type: application/json

{
  "date": "2024-08-17",
  "specialist": "MD House",
  "type": "Hospital",
  "description": "Hospital POST test",
  "discharge": {
    "date": "2024-08-18",
    "criteria": "Discharged"
  }
}
###
